id: I004DAD38
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T07:25:23+00:00'
last_modified: '2022-06-07T14:02:59.295382+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD53272
  title: གཙང་སྨན་ཡེ་ཤེས་བཟང་པོའི་གསུང་རྩོམ་གཅེས་བསྡུས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C404:
      image_group_id: I1PD53741
      title: ''
      total_pages: 432
      order: 1
      base_file: C404.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
