id: P001696
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 10:15:13.800154
source_metadata:
  id: bdr:W1PD53272
  title: གཙང་སྨན་ཡེ་ཤེས་བཟང་པོའི་གསུང་རྩོམ་གཅེས་བསྡུས
  author: ''
  volumes:
    396af8e36fe7467a87b4dc2041485a09:
      image_group_id: I1PD53741
      title: ''
      volume_number: 1
      total_pages: 432
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
